### ISSUE TITLE
Nissan GT-R by YCA-y97y

### ISSUE THREAD

**Issue by justalemon** [TheTofuShop/Vehicles#1]
🚗 **What is the make and model of the vehicle that you want to add?** (e.g. Toyota 86 or Subaru Impreza WRX)

Nissan GT-R

📋 **Where we can get the vehicle?** (needs to be a 5mods link)

https://www.gta5-mods.com/vehicles/2015-nissan-gtr-nismo-yca-y97y

🙋 **Why do you want this vehicle on the server?** (please add a concrete reason)

I feel that the server needs a couple of recent japanese cars, and this R35 is high quality with a good number of tuning parts and also supports liveries.

🔧 **Does this vehicle has tuning parts?** (like bumpers, roofs, hoods/bonnets)

Yes.

❓ **Is there something else that we need to know?** (bugs, missing texts, if is unlocked or not, etc)

No.

**Comment by TheAussie** [comment]
Vehicle is already in the server, just has a meme handling on it at the moment.

**Comment by justalemon** [comment]
I know, but the vehicle looks good and has a lot of customization options. It only needs a proper handling and is ready to go.

**Comment by TheAussie** [comment]
test
