### ISSUE TITLE
Evo III handling too grippy

### ISSUE THREAD

**Issue by mPrism** [TheTofuShop/Vehicles#10]
🚗 **What is the spawn model or name of the vehicle?** (e.g. zn6 or Toyota 86)

Lancer Evolution 3

🔧 **What exactly needs to be changed?** (use https://gtamods.com/wiki/Handling.meta for reference)

I'm testing the evo 3 on akina right now, and i can full throttle through alot of corners on the stock fresh spawned version of the car. i can only imagine how much faster this car can get if its upgraded. i feel like some oversteer on turning with a high speed can help add a feeling of discipline driving it

**Comment by SiirToast** [comment]
Test the car on multiple tracks with different types of layouts. That High Speed turning you call is around 120-130km/h on the first 2 corners which most cars can do, while others get to 170km/h speeds easily, evo 3 barely does 160, 165 at the longest straight on Akina. Try the EVO 6 for comparison

**Comment by TheAussie** [comment]
> Test the car on multiple tracks with different types of layouts. That High Speed turning you call is around 120-130km/h on the first 2 corners which most cars can do, while others get to 170km/h speeds easily, evo 3 barely does 160, 165 at the longest straight on Akina. Try the EVO 6 for comparison

It was deliberately adjusted for 198 - 200 KM/H top speed, so this makes sense that it struggles to get to 160 - 165, but i feel that cars should atleast have realistic top speed, so i will try and fix this, Thanks for the feedback @SiirToast 

> I'm testing the evo 3 on akina right now, and i can full throttle through alot of corners on the stock fresh spawned version of the car. i can only imagine how much faster this car can get if its upgraded. i feel like some oversteer on turning with a high speed can help add a feeling of discipline driving it

I would like to test this with you @mPrism.

**Comment by SiirToast** [comment]
After new update and testing on different tracks with different driving styles (Shomaru/Akina) I've come to the conclusion that:
- 0-160km/h speed is excessive compared to the 0-100km/h which is far from realistic for an EVO staying at a 7.5s +-.  (Higher RPM 2nd gear feels like 4th lower RPM)
- Understeering problems starting at 70km/h being most noticeable at 90km/h

**Comment by big-imp** [comment]
this car understeers like a dog trying to run on a kitchen floor

**Comment by TheAussie** [comment]
> After new update and testing on different tracks with different driving styles (Shomaru/Akina) I've come to the conclusion that:
> 
> * 0-160km/h speed is excessive compared to the 0-100km/h which is far from realistic for an EVO staying at a 7.5s +-.  (Higher RPM 2nd gear feels like 4th lower RPM)
> * Understeering problems starting at 70km/h being most noticeable at 90km/h


0-100 km/h (sec): | 5.5
-- | --


@SiirToast

**Comment by mPrism** [comment]
Evo III handling is too grippy













if you made it this far down tell the angry people its a **joke**, the car is **perfect** as is

oh fuck it didnt format right
