### ISSUE TITLE
Impreza WRX STi 

### ISSUE THREAD

**Issue by SiirToast** [TheTofuShop/Vehicles#13]
🚗 **What is the spawn model or name of the vehicle?** (e.g. zn6 or Toyota 86)

Subaru Impreza WRX STi (Hawkeye)

🔧 **What exactly needs to be changed?** (use https://gtamods.com/wiki/Handling.meta for reference)

- Acceleration makes sense
- Way too grippy, cornering is easy at 140km/h
- Excessive top speed, longest straight on Akina reaching 188km/h
- Maybe adding some more bodyroll to it?

**Comment by Rj137** [comment]
This is not an issue, this is a question. Please use the questions channel on the discord for stuff like this.

**Comment by TofuCook** [comment]
https://discordapp.com/channels/392665885703405570/502943919647096832/674215126727000065
