### ISSUE TITLE
AE86 Levin Hatch

### ISSUE THREAD

**Issue by SiirToast** [TheTofuShop/Vehicles#14]
🚗 **What is the spawn model or name of the vehicle?** (e.g. zn6 or Toyota 86)

Toyota AE86 Levin Hatch

🔧 **What exactly needs to be changed?** (use https://gtamods.com/wiki/Handling.meta for reference)

I think it needs a complete rework. Doesn't feel anything close to the Trueno
- Too much understeering
- Very low acceleration
- Braking is a bit underwhelming even for a such underpowered car

**Comment by mPrism** [comment]
nice update, idk how you got it to feel like the trueno does but you nailed it. good job, the car is great

**Comment by SiirToast** [comment]
After the new update the car feels good to drive, definitely resembles the Trueno. Just needs some minor tweaking for it to be identical to the Trueno. 
- Needs minor adjustment in fTractionCurveMax / fTractionCurveMin so it feels more drifty like the Trueno (if those are the values to make it grip less in the back wheels)
- Acceleration should be a bit lower to match the Trueno ( Trueno 9.5s - Levin 8.5s )

**Comment by TofuCook** [comment]
I cant comment for much but i can report that topseed is inferior by 20kph approx from the AE86 tho

**Comment by isemarcos** [comment]
I think it would be cool if is there a Takumi's 86 with 300hp, like in the anime.

**Comment by TheAussie** [comment]
I haven't heard anymore feedback on this issue, so i will assume it is good enough, i am closing it.
