### ISSUE TITLE
Mitsubishi GTO

### ISSUE THREAD

**Issue by SiirToast** [TheTofuShop/Vehicles#15]
🚗 **What is the spawn model or name of the vehicle?** (e.g. zn6 or Toyota 86)

Mitsubishi GTO

🔧 **What exactly needs to be changed?** (use https://gtamods.com/wiki/Handling.meta for reference)

**(Model issues)**
- Suspension not working? When switching between the different types the car doesn't get lowered.
- Wheels not changing, stuck on stock
- No visual mods

**(Handling)**
- A tiny bit higher acceleration (0.3s - 0.5s)
- Higher top speed, around the 180km/h range
- Reduce a bit fBrakeForce so it has a harder time braking since it's a very heavy car
- Overall very close to the real thing.

**Comment by TheAussie** [comment]
I have done the following:
* Adjusted acceleration a bit
* Changed braking force
@SiirToast
