### ISSUE TITLE
Peugeot 205 Turbo by dsawdsaw

### ISSUE THREAD

**Issue by SiirToast** [TheTofuShop/Vehicles#17]
🚗 **What is the make and model of the vehicle that you want to add?** (e.g. Toyota 86 or Subaru Impreza WRX)

Peugeot 205 Turbo (Non-rally version)

📋 **Where we can get the vehicle?** (needs to be a 5mods link)

https://www.gta5-mods.com/vehicles/peugeot-205-turbo-16-rally-2in1-add-on-tuning-livery

🙋 **Why do you want this vehicle on the server?** (please add a concrete reason)

We need more european cars since we barely have any, at least the most iconic ones from the 80s-90s.

🔧 **Does this vehicle has tuning parts?** (like bumpers, roofs, hoods/bonnets)

seats, cages, spoilers, rally-lights, mud-guard, front-skirts

❓ **Is there something else that we need to know?** (bugs, missing texts, if is unlocked or not, etc)

Add the normal version, not the rally one. yPG205t16B

**Comment by TofuCook** [comment]
Yes please, add, it was my first car ffs. :(

**Comment by TheAussie** [comment]
Vehicle has been added, this now requires some kind of feedback, but i feel it is already fun how it is.

spawncode is p205
