### ISSUE TITLE
Mitsubishi Lan Evo X by YCA-y97y

### ISSUE THREAD

**Issue by justalemon** [TheTofuShop/Vehicles#2]
🚗 **What is the make and model of the vehicle that you want to add?** (e.g. Toyota 86 or Subaru Impreza WRX)

Mitsubishi Lancer Evolution X FQ-400

📋 **Where we can get the vehicle?** (needs to be a 5mods link)

https://www.gta5-mods.com/vehicles/mitsubishi-lancer-evolution-x-fq-400
https://www.gta5-mods.com/vehicles/mitsubishi-lancer-evolution-x-fq-400-add-on-oiv-tuning

🙋 **Why do you want this vehicle on the server?** (please add a concrete reason)

As I said on #1, we need more recent japanese vehicles, and this evo is already on the server files so it just needs a handling.

🔧 **Does this vehicle has tuning parts?** (like bumpers, roofs, hoods/bonnets)

Yes, but very minimal.

❓ **Is there something else that we need to know?** (bugs, missing texts, if is unlocked or not, etc)

No.

**Comment by TheAussie** [comment]
![image](https://user-images.githubusercontent.com/19722293/72717143-9c989f00-3bc7-11ea-9e6b-058b3d45cbf5.png)
I believe this is the same vehicle?, if so it's already added, just need to fine-tune the handling.

**Comment by justalemon** [comment]
Yep, is the same vehicle.
