### ISSUE TITLE
Ford Sierra RS Cosworth by KAFAROS

### ISSUE THREAD

**Issue by SiirToast** [TheTofuShop/Vehicles#20]
🚗 **What is the make and model of the vehicle that you want to add?** (e.g. Toyota 86 or Subaru Impreza WRX)

1987 Ford Sierra RS Cosworth

📋 **Where we can get the vehicle?** (needs to be a 5mods link)

https://www.gta5-mods.com/vehicles/1987-ford-sierra-rs-cosworth-hq-tuning

🙋 **Why do you want this vehicle on the server?** (please add a concrete reason)

Because 90's rally legend

🔧 **Does this vehicle has tuning parts?** (like bumpers, roofs, hoods/bonnets)

It does have some. Not specified in post

❓ **Is there something else that we need to know?** (bugs, missing texts, if is unlocked or not, etc)

It's a replace, might be wonky to add

**Comment by Rj137** [comment]
Super low quality mod, also super rare import to Japan, would wait for a better model to come out.
