### ISSUE TITLE
Audi S4 by Mrjappie241

### ISSUE THREAD

**Issue by SiirToast** [TheTofuShop/Vehicles#21]
🚗 **What is the make and model of the vehicle that you want to add?** (e.g. Toyota 86 or Subaru Impreza WRX)

2000 Audi S4

📋 **Where we can get the vehicle?** (needs to be a 5mods link)

https://www.gta5-mods.com/vehicles/2000-audi-s4-add-on-replace

🙋 **Why do you want this vehicle on the server?** (please add a concrete reason)

We don't have a single Audi in the server, and we need more European cars

🔧 **Does this vehicle has tuning parts?** (like bumpers, roofs, hoods/bonnets)

Not much. I believe removing plates.

❓ **Is there something else that we need to know?** (bugs, missing texts, if is unlocked or not, etc)

Textures might not the best

**Comment by Rj137** [comment]
Horrible model, check to see if there is a better one. While these were imported to Japan, they were not as popular as more modern late 2000's early 2010's models.
