### ISSUE TITLE
Volkswagen Golf Mk2 by Gta5KoRn

### ISSUE THREAD

**Issue by SiirToast** [TheTofuShop/Vehicles#23]
🚗 **What is the make and model of the vehicle that you want to add?** (e.g. Toyota 86 or Subaru Impreza WRX)

Volkswagen Golf Mk2

📋 **Where we can get the vehicle?** (needs to be a 5mods link)

https://www.gta5-mods.com/vehicles/volkswagen-golf-mk2 or https://www.gta5-mods.com/vehicles/vw-golf-add-on-pack

🙋 **Why do you want this vehicle on the server?** (please add a concrete reason)

We got no VW's in the server, plus there is VW fanboys everywhere

🔧 **Does this vehicle has tuning parts?** (like bumpers, roofs, hoods/bonnets)

Doesn't look like it

❓ **Is there something else that we need to know?** (bugs, missing texts, if is unlocked or not, etc)

Texture quality might not be the best

**Comment by Rj137** [comment]
Very very low quality mods and models, would wait for a higher quality model release.
