### ISSUE TITLE
Porsche 930 feedback

### ISSUE THREAD

**Issue by doctorluke26** [TheTofuShop/Vehicles#26]
🚗 **What is the spawn model or name of the vehicle?** (e.g. zn6 or Toyota 86)

[Porsche 930]

🔧 **What exactly needs to be changed?** (use https://gtamods.com/wiki/Handling.meta for reference)

The Porsche feels to light when hitting a guardrail or doing little bumps.

**Comment by Rj137** [comment]
Porsche 930's suspension was edited to act more slowly but not effect anything else, this should fix the issue
