### ISSUE TITLE
Nissan Sil80 - First person mirrors are disco balls

### ISSUE THREAD

**Issue by Sashraan** [TheTofuShop/Vehicles#27]
The Sil80's mirrors - when viewed in first person - do not reflect properly. They seem either extremely low resolution (very few pixels shown) or like their reflection is using a disco ball / fly's eye texture that breaks up the image into several dozen chunks.

See images below :
Right : https://cdn.discordapp.com/attachments/636314924112543744/673279422551425055/Capture2473_window_FiveM_GTAProcess_on_2020-02-01_at16-31-22.jpg

Rear-view : https://cdn.discordapp.com/attachments/636314924112543744/673284268742410271/Capture2474_window_FiveM_GTAProcess_on_2020-02-01_at16-31-33.jpg

Left : https://cdn.discordapp.com/attachments/636314924112543744/673284295150010389/Capture2475_window_FiveM_GTAProcess_on_2020-02-01_at16-31-39.jpg

**Comment by Rj137** [comment]
We cannot fix mirrors as we don't know how to, and the models are also locked, meaning we can not edit them whatsoever.
