### ISSUE TITLE
Mercedes-Benz W140 AMG by ANeRTee

### ISSUE THREAD

**Issue by Renaultthebigboy** [TheTofuShop/Vehicles#3]
🚗 **What is the make and model of the vehicle that you want to add?** (e.g. Toyota 86 or Subaru Impreza WRX)

Mercedes-Benz W140 AMG 

📋 **Where we can get the vehicle?** (needs to be a 5mods link)

https://www.gta5-mods.com/vehicles/mercedes-benz-w140-amg

🙋 **Why do you want this vehicle on the server?** (please add a concrete reason)

I mean, we have only 3 EU cars and 0 mercedes, even tho it was in the Initial D and was pretty popular in Japan.

🔧 **Does this vehicle has tuning parts?** (like bumpers, roofs, hoods/bonnets)

I believe it does, yes.

❓ **Is there something else that we need to know?** (bugs, missing texts, if is unlocked or not, etc)

I don't think so.

**Comment by TheAussie** [comment]
Is this car not just the same as this? 
![image](https://user-images.githubusercontent.com/19722293/72720533-4bd87480-3bce-11ea-94ec-33eb94a217dd.png)

![image](https://user-image.githubusercontent.com/19722293/72720550-5561dc80-3bce-11ea-84e2-e2e6e29baef8.png)
 @Renaultthebigboy

**Comment by Rj137** [comment]
This exact car is already in the server and is publicly spawnable.

**Comment by Rj137** [comment]
close #3
