### ISSUE TITLE
BMW Z8 by Kpym

### ISSUE THREAD

**Issue by SiirToast** [TheTofuShop/Vehicles#34]
🚗 **What is the make and model of the vehicle that you want to add?** (e.g. Toyota 86 or Subaru Impreza WRX)

BMW Z8

📋 **Where we can get the vehicle?** (needs to be a 5mods link)

https://www.gtainside.com/en/gta5/cars/124363-bmw-z8-add-on-replace/

🙋 **Why do you want this vehicle on the server?** (please add a concrete reason)

European miata. But actually fast. Variety

🔧 **Does this vehicle has tuning parts?** (like bumpers, roofs, hoods/bonnets)

Doesn't look like it

❓ **Is there something else that we need to know?** (bugs, missing texts, if is unlocked or not, etc)

Nope

**Comment by Rj137** [comment]
not a 5mods link
