### ISSUE TITLE
22B

### ISSUE THREAD

**Issue by HuntCunt** [TheTofuShop/Vehicles#38]
🚗 **What is the spawn model or name of the vehicle?** (e.g. zn6 or Toyota 86)

sim22

🔧 **What exactly needs to be changed?** (use https://gtamods.com/wiki/Handling.meta for reference)

with ur new update of the car the thing just became no fun anymore, it just another OP fast car with no fun factor behind it anymore. what i would like is to keep the old handeling wiht the shitty top speed, so duals vs fds or any other car stays fun.

**Comment by TheAussie** [comment]
This is feedback I can't use, It is just you whining about the car.

"OP fastcar", How is it op?.

I am not a mind reader.
