### ISSUE TITLE
You probably won’t like it

### ISSUE THREAD

**Issue by maruchan1** [TheTofuShop/Vehicles#4]
Concerns all cars

🔧 Although I am not sure if this is possible, a test of this would be great. If all the “OP” high horsepower cars felt heavier and more sluggish, overall cornering at a lower speed, and the low horsepower cars like the Civic EG and the AE86 were faster in and out of corners. The handling would have to be very close and if not, identical. Similar to Initial D Arcade. Disregarding the real cars handling will be the hardest part about this, but I feel that a more fun playing experience would be the outcome. Playing around with inverse power may give the desired outcome if possible

**Comment by TheAussie** [comment]
This server is no associated with Initial D Arcade, so why would i make the handling like Initial D arcade?

**Comment by maruchan1** [comment]
It’d make racing feel more balanced rather than having all cars fly through corners fast as fuck and making it a personal preference on your drive type. There’s no use making the cars handle realistic when it’s FiveM using rage engine

**Comment by TheAussie** [comment]
.... I don't know what cars you have been driving, but they don't "fly" through corners... As you claim.
