### ISSUE TITLE
Nissan 180SX by cereaI

### ISSUE THREAD

**Issue by Rj137** [TheTofuShop/Vehicles#45]
🚗 **What is the make and model of the vehicle that you want to add?** (e.g. Toyota 86 or Subaru Impreza WRX)

Nissan 180SX

📋 **Where we can get the vehicle?** (needs to be a 5mods link)

https://www.gta5-mods.com/vehicles/nissan-180sx-add-on-tuning

🙋 **Why do you want this vehicle on the server?** (please add a concrete reason)

Replace the old 180sx

🔧 **Does this vehicle has tuning parts?** (like bumpers, roofs, hoods/bonnets)

Yes, too many.

❓ **Is there something else that we need to know?** (bugs, missing texts, if is unlocked or not, etc)

Its stock, unlike the one already in the server and the one in the server lags everyone every time it collides with anything. This is a non negotiable, replace the old one with this one.

**Comment by TheAussie** [comment]
This has been added, has no handling and isn't in the menu yet.
