### ISSUE TITLE
R35 is too slow, not grippy enough and suspension is loose

### ISSUE THREAD

**Issue by big-imp** [TheTofuShop/Vehicles#5]
🚗 **What is the spawn model or name of the vehicle?** (e.g. zn6 or Toyota 86)

r35

🔧 **What exactly needs to be changed?** (use https://gtamods.com/wiki/Handling.meta for reference)

The r35 currently feels too slow compared to its irl car. It's also not grippy enough in corners compared to its real version. Suspension feels a little loose.

**Comment by TheAussie** [comment]
```xml
<?xml version="1.0" encoding="UTF-8"?>

<CHandlingDataMgr>
  <HandlingData>
    <Item type="CHandlingData">
      <handlingName>r35</handlingName>
      <fInitialDragCoeff value="8.500000" /> -- Sets the drag coefficient on the rage physics archetype of the vehicle (proportional to velocity squared). Increase to simulate aerodynamic drag.
      <fInitialDriveForce value="0.320000" /> -- This multiplier modifies the game's calculation of drive force (from the output of the transmission).
      <fInitialDriveMaxFlatVel value="170.000000" />-- Determines the speed at redline in top gear. Setting this value does not guarantee the vehicle will reach this speed. Multiply the number in the file by 0-82 to get the speed in mph or multiply by 1.32 to get kph
      <fSteeringLock value="28.000000" /> -- This one is obvious
      <fTractionCurveMax value="2.000000" /> -- Traction Modifier when making a corner
      <fTractionCurveMin value="2.150000" /> -- Traction Modifier when accelerating and braking
      <fTractionCurveLateral value="23.500000" />-- Shape of lateral traction curve (peak traction position in degrees).
      <fSuspensionForce value="2.800000" />-- 1 / (Force * NumWheels) = Lower limit for zero force at full extension. Affects how strong suspension is. Can help if car is easily flipped over when turning.
      <fSuspensionCompDamp value="1.55000" />-- Damping during strut compression. Bigger = stiffer.
      <fSuspensionReboundDamp value="2.130000" /> -- Damping during strut rebound. Bigger = stiffer
      <fAntiRollBarForce value="0.500000" /> -- The spring constant that is transmitted to the opposite wheel when under compression larger numbers are a larger force. Larger Numbers = less body roll
      <fAntiRollBarBiasFront value="0.500000" />-- The bias between front and rear for the antiroll bar(0 front, 1 rear)
      <fRollCentreHeightFront value="0.075000" /> -- This value modify the weight transmission during an acceleration between the left and right. I REALLY recommend to be very careful while modifying it, because it's very sensitive and can ruin your driving control. Larger Numbers = less rollover opportunity (drive like on rails)

A negative value will make the weight more important at the opposite direction when you accelerate, and a positive will make your weight more important on the same direction you're going.

A positive value is visually unrealistic, so i don't recommend to do it.

Best to do is to only go between 0.15/-0.15.
      <fRollCentreHeightRear value="0.075000" /> -- This value modify the weight transmission during an acceleration between the front and rear (and can affect the acceleration speed). I REALLY recommend to be very careful while modifying it, because it's very sensitive and can ruin your driving control (a high positive value can make your car able to do wheelies, but you won't be able to control it if you turn your wheel). Larger Numbers = less rollover opportunity (drive like on rails)

A negative value will make the weight more important at the rear when you accelerate, and a positive will make your weight more important on the front.

A positive value is visually unrealistic, so i don't recommend to do it.

Best to do is to only go between 0.15/-0.15.
  </HandlingData>
</CHandlingDataMgr>
```

@big-imp 

Have a look at this, tell me what you think i should change xD.

**Comment by big-imp** [comment]
@TheAussie 
i have copy pasted and replaced the values of what i think you should change for ease of use 

1. <fInitialDragCoeff value="5.500000" /> (the specs i found says the drag coefficient is 0.26 so idk how this number compares to its actual stat)
2. <fInitialDriveForce value="0.600000" />
3.   <fInitialDriveMaxFlatVel value="239.030000" /> (with the given calculation this gives the car its actual top speed)
4. <fSteeringLock value="30.000000" />
5. <fTractionCurveMax value="1.500000" />
6. <fTractionCurveMin value="1.750000" />
7. <fTractionCurveLateral value="25.00000" />
8. <fSuspensionForce value="2.500000" /> (?)
9. <fSuspensionCompDamp value="1.9000" />
10. <fSuspensionReboundDamp value="2.300000" /> 
11. <fAntiRollBarForce value="0.750000" />
12. <fAntiRollBarBiasFront value="0.750000" />
13. <fRollCentreHeightFront value="0.080000" />

idk how these stats will scale but this car's stats are insane and should be insane in-game aswell

**Comment by big-imp** [comment]
@TheAussie 
I copy pasted the values and replaced them for ease of use
`<fInitialDragCoeff value="5.500000" />` (the actual drag coef. is 0.26, so idk how this value will actually scale to the real stat)
`<fInitialDriveForce value="0.60000" />`
`<fInitialDriveMaxFlatVel value="239.030000" />`
`<fSteeringLock value="30.000000" />`
`<fTractionCurveMax value="1.500000" />`
`<fTractionCurveMin value="1.750000" />`
`<fTractionCurveLateral value="25.500000" />`
`fSuspensionForce value="3.000000" />`
`<fSuspensionCompDamp value="1.85000" />`
`<fSuspensionReboundDamp value="2.500000" />`
`<fAntiRollBarForce value="0.750000" />`
`<fAntiRollBarBiasFront value="0.750000" />`
`<fRollCentreHeightFront value="0.085000" />`

this car's stats are really nutty, so this is gonna be a fast boi with its stats
