### ISSUE TITLE
[Mazda RX-7] by [TGIJ]

### ISSUE THREAD

**Issue by KingFC01** [TheTofuShop/Vehicles#50]
🚗 **What is the make and model of the vehicle that you want to add?** (e.g. Toyota 86 or Subaru Impreza WRX)

[Mazda RX-7]

📋 **Where we can get the vehicle?** (needs to be a 5mods link)

https://gta5-mods.com/vehicles/mazda-rx-7-super-tuning-add-on

🙋 **Why do you want this vehicle on the server?** (please add a concrete reason)

[Well, the actual RX-7 only has the re-amemiya kit and with this one you can create the Keisuke's FD from Stage 1 & 2 and also Kyoko's FD. Besides that, the car has more than 200 parts including kits to use, so it would be great.]

🔧 **Does this vehicle has tuning parts?** (like bumpers, roofs, hoods/bonnets)

[Yes, more than 200 parts]

❓ **Is there something else that we need to know?** (bugs, missing texts, if is unlocked or not, etc)

[As in the page says: The two rear doors control pop lights and light dummys, so if you have tuned lights and want the light cast on the ground to be correct, open two rear doors]

**Comment by TheAussie** [comment]
not adding
