### ISSUE TITLE
Nissan GT-R R32

### ISSUE THREAD

**Issue by doctorluke26** [TheTofuShop/Vehicles#51]
🚗 **What is the make and model of the vehicle that you want to add?** (e.g. Toyota 86 or Subaru Impreza WRX)

Nissan Skyline GT-R R32

📋 **Where we can get the vehicle?** (needs to be a 5mods link)

https://www.gta5-mods.com/vehicles/nissan-skyline-r32-add-on-tuning-template/download/73905

🙋 **Why do you want this vehicle on the server?** (please add a concrete reason)

This has much more customisation then the current R32

🔧 **Does this vehicle has tuning parts?** (like bumpers, roofs, hoods/bonnets)

Yes

❓ **Is there something else that we need to know?** (bugs, missing texts, if is unlocked or not, etc)

Nope

**Comment by Rj137** [comment]
we decided no on this model for many reasons a long time ago. if we get a new r32, we are going to be the ones to convert it to gta.
