### ISSUE TITLE
1999 Dodge Viper GTS ACR by tk0wnz

### ISSUE THREAD

**Issue by SomeBooty** [TheTofuShop/Vehicles#6]
🚗 **What is the make and model of the vehicle that you want to add?** (e.g. Toyota 86 or Subaru Impreza WRX)

Dodge Viper GTS ACR

📋 **Where we can get the vehicle?** (needs to be a 5mods link)

https://www.gta5-mods.com/vehicles/1999-dodge-viper-gts-acr

🙋 **Why do you want this vehicle on the server?** (please add a concrete reason)

U have no american cars 

🔧 **Does this vehicle has tuning parts?** (like bumpers, roofs, hoods/bonnets)

Yeah of course

❓ **Is there something else that we need to know?** (bugs, missing texts, if is unlocked or not, etc)
nah man besides its locked ofc

**Comment by TheAussie** [comment]
I have some american cars.
Belair, Vega, diplomat.
