### ISSUE TITLE
2003 Renault Clio V6 by baba0rum

### ISSUE THREAD

**Issue by SiirToast** [TheTofuShop/Vehicles#9]
🚗 **What is the make and model of the vehicle that you want to add?** (e.g. Toyota 86 or Subaru Impreza WRX)

2003 Renault Clio V6 Phase 2

📋 **Where we can get the vehicle?** (needs to be a 5mods link)

https://www.gta5-mods.com/vehicles/2003-renault-clio-v6-phase-2-tuning

🙋 **Why do you want this vehicle on the server?** (please add a concrete reason)

Because rear engine and rwd = deathwishmobile + Euro car

🔧 **Does this vehicle has tuning parts?** (like bumpers, roofs, hoods/bonnets)

2 Front bumper
1 Rear bumper
2 Spoiler

❓ **Is there something else that we need to know?** (bugs, missing texts, if is unlocked or not, etc)

No idea if unlocked, tried installing it myself and failed miserably. Might have crash issues

**Comment by TheAussie** [comment]
This model isn't particularly good..
